Repository Mojang/minecraft-debugger, pull requests merged in 2024-07, with the labels that each got.

#79 feat(packaging): Added semantic-release to the repository
  .github/workflows/ci.yml
  .github/workflows/release.yml
  CHANGELOG_old.md
  package-lock.json
  package.json
  webview-ui/package-lock.json
  webview-ui/package.json
Labels: feat

#80 chore: Deleted old changelog
  CHANGELOG_old.md
Labels: chore

#81 chore(ci): Deleted old ADO build pipelines
  .ado/ci_build.yml
  .ado/templates/package_extension.yml
Labels: chore

#84 fix(sourcemaps): In-line source maps with charset would fail to be loaded
  src/SourceMaps.ts
Labels: fix

#82 feat(diagnostics): Add Client Subscriber Stats UI
  webview-ui/src/diagnostics_panel/App.tsx
  webview-ui/src/diagnostics_panel/StatisticProvider.tsx
  webview-ui/src/diagnostics_panel/controls/MinecraftStatisticStackedBarChart.tsx
Labels: feat

#86 fix(changelogs): Updated changelog release semantics
  .github/workflows/release.yml
  package.json
  release.config.js
Labels: fix

#89 fix(ci): Update publishing pipeline to Azure CLI to authenticate with VSCE
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: fix

#90 chore(build): Added bundling via esbuild
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  esbuild.js
  package-lock.json
  package.json
Labels: chore

#91 fix(build): Fixed issue where extra files were included in the extension, bloating the size of the extension ~2x.
  .vscodeignore
Labels: fix

#92 chore(ci): Added Dependabot auto update configuration
  .github/dependabot.yml
Labels: chore

#102 chore(ci): Updated dependabot commit titles to include semantic release tags
  .github/dependabot.yml
Labels: chore

#108 chore(ci): Add auto-approve for Dependabot PRs
  .github/workflows/auto-approve-dependabot.yml
Labels: chore

#109 chore(build): Fix targeted VS Code version in manifest
  package-lock.json
  package.json
Labels: chore

#113 chore(packaging): Updated version in package.json to `0.0.0-semantically-released`
  package-lock.json
  package.json
Labels: chore

#115 fix(build): Source maps would not load due to missing `mappings.wasm` file (fixes #114)
  esbuild.mjs
  package-lock.json
  package.json
  src/SourceMaps.ts
Labels: fix

#116 feat(diagnostics): Updated stat names to not be all lowercase
  src/StatsProvider2.ts
  src/panels/MinecraftDiagnostics.ts
  webview-ui/src/diagnostics_panel/StatisticProvider.tsx
  webview-ui/src/diagnostics_panel/StatisticResolver.tsx
Labels: feat
